# Generated by Django 4.1.3 on 2022-12-20 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=6)),
                ('TemperatureA', models.IntegerField(validators=[django.core.validators.MinValueValidator(32), django.core.validators.MaxValueValidator(42)])),
                ('TemperatureB', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('Condition', models.BooleanField()),
                ('Q1', models.BooleanField()),
                ('Q2', models.BooleanField()),
                ('FreeText', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
