# Generated by Django 4.1.3 on 2022-12-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Condition',
        ),
    ]
