# Generated by Django 4.1.3 on 2023-01-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_remove_user_condition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='QBTModel',
        ),
    ]
