# Generated by Django 4.1.3 on 2023-01-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_rename_user_qbtmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbtmodel',
            name='StudentID',
            field=models.CharField(max_length=150),
        ),
    ]
